### ISSUE TITLE
Difference between Canyon's async chunk io and CraftBukkit's async chunk io implementation

### ISSUE THREAD

**Issue by nadecancode** [canyonmodded/canyon#43]
Hi, I want to know about the difference between Canyon's async chunk io and CraftBukkit's.

It seems like the algorithms do not have many differences, but could you tell me the distinctions between those? I'm appreciated :)

**Comment by astei** [comment]
Modern CraftBukkit (up to about 1.12.2, I don't know about when the async I/O system was first introduced)'s async I/O system was developed before `CompletableFuture` arrived in JDK 8. Instead there was a homebrew multi-stage runner system that attempted to load the chunk from disk in a separate thread pool and if that succeeded it would initialize the chunk (or else generate it).

Canyon's async chunk I/O system works in a similar fashion: it accepts chunk requests from the main thread, reads the chunk from disk on a separate thread, and then returns to the main thread to complete the load (or generation process).

There aren't a lot of differences. Probably the most notable is that if a chunk load would block the main thread, Canyon will still fetch the chunk using a thread pool (so that other chunk requests can continue) but once the I/O for the chunk load that is blocking the main thread is complete, it immediately finishes the chunk loading in the main thread and then returns control to the NMS/OBC code. Likewise, if there is a load request in-flight and the main thread needs the chunk immediately, Canyon will notice this and return control to the main thread as soon as possible once the I/O has completed and let the main thread complete the chunk load. In this sense, the Canyon async I/O system works more like the async chunk loading in Paper 1.13+.

I hope this answers your question.
